title: Issabel Averina
logo: assets/ProfilePic.jpg
description: "Email: issabelaverina18@gmail.com  www.linkedin.com/in/issabelaverina"
theme: jekyll-theme-minima
header_pages:
  - about.md
  - experience.md
  - portfolio.md
