title: Issabel Averina
logo: /assets/ProfilePic.jpg
description: Aspiring Data Professional | Email: issabelaverina18@gmail.com | [LinkedIn](https://www.linkedin.com/in/issabelaverina)
theme: jekyll-theme-minima
header_pages:
  - about.md
  - experience.md
  - portfolio.md
