title: Issabel Averina
#logo: Profile .png
description: Hi! I'm Issabel, someone who desires to create a meaningful impact in the world through my works.
#show_downloads: true
theme: jekyll-theme-minimal
